version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: meska
      MYSQL_DATABASE: student_demo_hibernate
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data: